
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Patrol 5M      <small><?= cclang('detail', ['Patrol 5M']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/patrol_5m'); ?>">Patrol 5M</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Patrol 5M</h3>
                     <h5 class="widget-user-desc">Detail Patrol 5M</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_patrol_5m" id="form_patrol_5m" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->date); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Gerbang Masuk </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->gerbang_masuk); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Office </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->office); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Fasilitas Umum </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->fasilitas_umum); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Produksi Upstream </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->produksi_upstream); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Produksi Downstream </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->produksi_downstream); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Laboraturium </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->laboraturium); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Gudang </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->gudang); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Utility </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->utility); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">User Id </label>

                        <div class="col-sm-8">
                           <?= _ent($patrol_5m->user_id); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('patrol_5m_update', function() use ($patrol_5m){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit patrol_5m (Ctrl+e)" href="<?= site_url('administrator/patrol_5m/edit/'.$patrol_5m->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Patrol 5m']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/patrol_5m/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Patrol 5m']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
