<style type="text/css">

  input[type="file"] {
    display: none;
}
  .custom-file-upload {
      border: 1px solid #ccc;
      display: inline-block;
      padding: 6px 12px; 
      cursor: pointer;
  }
</style>

<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Trx_qbd/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('trx_qbd') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('trx_qbd') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('trx_qbd_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('trx_qbd')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/trx_qbd/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('trx_qbd')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('trx_qbd_export', function(){?>
                        <a class="btn btn-flat btn-success" href="<?= site_url('administrator/trx_qbd/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('trx_qbd_export', function(){?>
                        <!-- <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('trx_qbd') ?>']); ?>" href="<?= site_url('administrator/trx_qbd/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a> -->
                        <?php }) ?>
                        <label class="custom-file-upload btn btn-flat btn-success">
                            <input type='file' name='inputfile' id='inputfile'>
                            <i class="fa fa-cloud-upload"></i> Import Excel
                        </label> 
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('trx_qbd') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('trx_qbd')]); ?>  <i class="label bg-yellow"><?= $trx_qbd_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  

                  <form name="form_trx_qbd" id="form_trx_qbd" action="<?= base_url('administrator/trx_qbd/index'); ?>">
                  
                  <div class="row pb-20">
                  <div class="col-sm-12">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <!-- <option value="">Bulk</option> -->
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-2 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-1 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <!-- <option <?= $this->input->get('f') == 'date' ? 'selected' :''; ?> value="date">Date</option> -->
                           <option <?= $this->input->get('f') == 'deo_ffa' ? 'selected' :''; ?> value="deo_ffa">Deo Ffa</option>
                           <option <?= $this->input->get('f') == 'deo_bci' ? 'selected' :''; ?> value="deo_bci">Deo Bci</option>
                           <option <?= $this->input->get('f') == 'deo_ai' ? 'selected' :''; ?> value="deo_ai">Deo Ai</option>
                           <option <?= $this->input->get('f') == 'deo_red' ? 'selected' :''; ?> value="deo_red">Deo Red</option>
                           <option <?= $this->input->get('f') == 'deo_yellow' ? 'selected' :''; ?> value="deo_yellow">Deo Yellow</option>
                           <option <?= $this->input->get('f') == 'deo_blue' ? 'selected' :''; ?> value="deo_blue">Deo Blue</option>
                           <option <?= $this->input->get('f') == 'deo_neutral' ? 'selected' :''; ?> value="deo_neutral">Deo Neutral</option>
                           <option <?= $this->input->get('f') == 'raw_ffa' ? 'selected' :''; ?> value="raw_ffa">Raw Ffa</option>
                           <option <?= $this->input->get('f') == 'raw_bci' ? 'selected' :''; ?> value="raw_bci">Raw Bci</option>
                           <option <?= $this->input->get('f') == 'raw_ai' ? 'selected' :''; ?> value="raw_ai">Raw Ai</option>
                           <option <?= $this->input->get('f') == 'raw_red' ? 'selected' :''; ?> value="raw_red">Raw Red</option>
                           <option <?= $this->input->get('f') == 'raw_yellow' ? 'selected' :''; ?> value="raw_yellow">Raw Yellow</option>
                           <option <?= $this->input->get('f') == 'raw_blue' ? 'selected' :''; ?> value="raw_blue">Raw Blue</option>
                           <option <?= $this->input->get('f') == 'raw_neutral' ? 'selected' :''; ?> value="raw_neutral">Raw Neutral</option>
                          </select>
                     </div>
                     <div class="col-sm-2">
                      <input type="text" id="tanggal_awal" name="tanggal_awal" value="<?= $default_awal ?>" class="form-control datepicker" placeholder="Start Date">
                    </div>
                    <div class="col-sm-2">
                      <input type="text" id="tanggal_akhir" name="tanggal_akhir" value="<?= $default_akhir ?>" class="form-control datepicker" placeholder="End Date">
                    </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/trx_qbd');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
               </div>

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable" id="datatable_olam">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th> <?= cclang('date') ?></th>
                           <th> <?= cclang('deo_ffa') ?></th>
                           <th> <?= cclang('deo_bci') ?></th>
                           <th> <?= cclang('deo_ai') ?></th>
                           <th> <?= cclang('deo_red') ?></th>
                           <th> <?= cclang('deo_yellow') ?></th>
                           <th> <?= cclang('deo_blue') ?></th>
                           <th> <?= cclang('deo_neutral') ?></th>
                           <th> <?= cclang('raw_ffa') ?></th>
                           <th> <?= cclang('raw_bci') ?></th>
                           <th> <?= cclang('raw_ai') ?></th>
                           <th> <?= cclang('raw_red') ?></th>
                           <th> <?= cclang('raw_yellow') ?></th>
                           <th> <?= cclang('raw_blue') ?></th>
                           <th> <?= cclang('raw_neutral') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_trx_qbd">
                     <?php foreach($trx_qbds as $trx_qbd): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $trx_qbd->id; ?>">
                           </td>
                                                       
                           <td><?= date("d M Y", strtotime($trx_qbd->date)); ?></td> 
                           <td><?= number_format($trx_qbd->deo_ffa, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->deo_bci, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->deo_ai, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->deo_red, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->deo_yellow, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->deo_blue, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->deo_neutral, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->raw_ffa, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->raw_bci, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->raw_ai, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->raw_red, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->raw_yellow, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->raw_blue, 2, ',', ' ') ?></td> 
                           <td><?= number_format($trx_qbd->raw_neutral, 2, ',', ' ') ?></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('trx_qbd_view', function() use ($trx_qbd){?>
                                 <!-- <a href="<?= site_url('administrator/trx_qbd/single_pdf/' .$trx_qbd->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?> -->
                              <!-- <a href="<?= site_url('administrator/trx_qbd/view/' . $trx_qbd->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?> -->
                              <?php }) ?>
                              <?php is_allowed('trx_qbd_update', function() use ($trx_qbd){?>
                              <a href="<?= site_url('administrator/trx_qbd/edit/' . $trx_qbd->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('trx_qbd_delete', function() use ($trx_qbd){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/trx_qbd/delete/' . $trx_qbd->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($trx_qbd_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Quality Butter DEO data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <!-- <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'date' ? 'selected' :''; ?> value="date">Date</option>
                           <option <?= $this->input->get('f') == 'deo_ffa' ? 'selected' :''; ?> value="deo_ffa">Deo Ffa</option>
                           <option <?= $this->input->get('f') == 'deo_bci' ? 'selected' :''; ?> value="deo_bci">Deo Bci</option>
                           <option <?= $this->input->get('f') == 'deo_ai' ? 'selected' :''; ?> value="deo_ai">Deo Ai</option>
                           <option <?= $this->input->get('f') == 'deo_red' ? 'selected' :''; ?> value="deo_red">Deo Red</option>
                           <option <?= $this->input->get('f') == 'deo_yellow' ? 'selected' :''; ?> value="deo_yellow">Deo Yellow</option>
                           <option <?= $this->input->get('f') == 'deo_blue' ? 'selected' :''; ?> value="deo_blue">Deo Blue</option>
                           <option <?= $this->input->get('f') == 'deo_neutral' ? 'selected' :''; ?> value="deo_neutral">Deo Neutral</option>
                           <option <?= $this->input->get('f') == 'raw_ffa' ? 'selected' :''; ?> value="raw_ffa">Raw Ffa</option>
                           <option <?= $this->input->get('f') == 'raw_bci' ? 'selected' :''; ?> value="raw_bci">Raw Bci</option>
                           <option <?= $this->input->get('f') == 'raw_ai' ? 'selected' :''; ?> value="raw_ai">Raw Ai</option>
                           <option <?= $this->input->get('f') == 'raw_red' ? 'selected' :''; ?> value="raw_red">Raw Red</option>
                           <option <?= $this->input->get('f') == 'raw_yellow' ? 'selected' :''; ?> value="raw_yellow">Raw Yellow</option>
                           <option <?= $this->input->get('f') == 'raw_blue' ? 'selected' :''; ?> value="raw_blue">Raw Blue</option>
                           <option <?= $this->input->get('f') == 'raw_neutral' ? 'selected' :''; ?> value="raw_neutral">Raw Neutral</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/trx_qbd');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div> -->
                  </form>                  <div class="col-md-4 pull-right">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_trx_qbd').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/trx_qbd/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>

<script type="text/javascript">
  $(document).ready(function() {
    $('#inputfile').change(function(){
        var file_data = $('#inputfile').prop('files')[0];   
        var form_data = new FormData();                  
        form_data.append('file', file_data);
        $.ajax({
            url: "<?=  site_url('administrator/trx_qbd/import_excel'); ?>",
            type: "POST",
            data: form_data,
            contentType: false,
            cache: false,
            processData:false,
            success: function(data){
                // console.log(data);
                window.location.reload();
            }
        });
    });
});
</script>